version: "2"
run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: true
linters:
  enable:
    - dupl
    - gocyclo
    - misspell
    - revive
    - gosec # Security checks
    - unused # Unused code detection
  disable:
    - asasalint
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - exhaustive
    - forbidigo
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godox
    - goheader
    - goprintffuncname
    - lll
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - rowserrcheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    gofmt:
      simplify: true
    gosec:
      confidence: medium
      severity: medium
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: var-naming
        - name: indent-error-flow
        - name: error-naming
        - name: if-return
        - name: import-shadowing
        - name: range-val-address
        - name: time-naming
        - name: unexported-return
        - name: unused-parameter
        - name: unused-receiver
        - name: var-declaration
        - name: exported
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: error-strings
        - name: error-return
        - name: errorf
        - name: function-length
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocyclo
          - revive
        path: .*_test\.go$
      - path: .*_test\.go$
        text: function-length
      - path: .*_test\.go$
        text: cyclomatic complexity
    paths:
      - .*_gen.go$
      - .*_mock.go$
      - dist
      - vendor
      - .git
      - .github
      - .vscode
      - .idea
      - node_modules
      - testdata
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - .*_gen.go$
      - .*_mock.go$
      - dist
      - vendor
      - .git
      - .github
      - .vscode
      - .idea
      - node_modules
      - testdata
      - third_party$
      - builtin$
      - examples$
