version: 2
project_name: openmorph
builds:
  - main: ./main.go
    binary: openmorph
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'github.com/developerkunal/OpenMorph/cmd.version={{.Tag}}'
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: developerkunal
    name: OpenMorph

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/developerkunal/openmorph:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=TARGETARCH=amd64"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - internal/
  - image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-arm64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-arm64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/developerkunal/openmorph:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=TARGETARCH=arm64"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - internal/
  - image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-distroless"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-distroless"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-distroless"
    dockerfile: Dockerfile.distroless
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=TARGETARCH=amd64"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - internal/
  - image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-distroless-arm64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-distroless-arm64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-distroless-arm64"
    dockerfile: Dockerfile.distroless
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=TARGETARCH=arm64"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - internal/

  # Add dev variant Docker builds
  - image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-dev-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-dev-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-dev-amd64"
      - "ghcr.io/developerkunal/openmorph:latest-dev-amd64"
    dockerfile: Dockerfile.dev
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=TARGETARCH=amd64"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - internal/
  - image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-dev-arm64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-dev-arm64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-dev-arm64"
      - "ghcr.io/developerkunal/openmorph:latest-dev-arm64"
    dockerfile: Dockerfile.dev
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=TARGETARCH=arm64"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - internal/

# Docker manifests for multi-platform support
docker_manifests:
  - name_template: "ghcr.io/developerkunal/openmorph:{{ .Tag }}"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-amd64"
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:v{{ .Major }}"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:latest"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:latest-amd64"
      - "ghcr.io/developerkunal/openmorph:latest-arm64"
  # Distroless multi-platform manifests
  - name_template: "ghcr.io/developerkunal/openmorph:{{ .Tag }}-distroless"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-distroless"
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-distroless-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:v{{ .Major }}-distroless"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-distroless"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-distroless-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-distroless"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-distroless"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-distroless-arm64"
  # Dev multi-platform manifests
  - name_template: "ghcr.io/developerkunal/openmorph:{{ .Tag }}-dev"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-dev-amd64"
      - "ghcr.io/developerkunal/openmorph:{{ .Tag }}-dev-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:v{{ .Major }}-dev"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-dev-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}-dev-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-dev"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-dev-amd64"
      - "ghcr.io/developerkunal/openmorph:v{{ .Major }}.{{ .Minor }}-dev-arm64"
  - name_template: "ghcr.io/developerkunal/openmorph:latest-dev"
    image_templates:
      - "ghcr.io/developerkunal/openmorph:latest-dev-amd64"
      - "ghcr.io/developerkunal/openmorph:latest-dev-arm64"

# Homebrew tap
brews:
  - name: openmorph
    homepage: "https://github.com/developerkunal/OpenMorph"
    description: "A tool for transforming and optimizing OpenAPI specifications"
    license: "MIT"
    repository:
      owner: developerkunal
      name: homebrew-openmorph
      branch: main
      token: "{{ .Env.PACKAGE_MANAGER_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    test: |
      system "#{bin}/openmorph --version"
    install: |
      bin.install "openmorph"

# Scoop bucket
scoops:
  - name: openmorph
    homepage: "https://github.com/developerkunal/OpenMorph"
    description: "A tool for transforming and optimizing OpenAPI specifications"
    license: "MIT"
    repository:
      owner: developerkunal
      name: scoop-openmorph
      branch: main
      token: "{{ .Env.PACKAGE_MANAGER_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: bucket
