# GoReleaser config for OpenMorph
project_name: transform-openapi
builds:
  - main: ./main.go
    binary: transform-openapi
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README.md
      - .openapirc.yaml
      - cmd/
      - internal/
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: kunal-dawar
    name: OpenMorph
