project_name: openmorph
builds:
  - main: ./main.go
    binary: openmorph
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'main.version={{.Tag}}'
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - "{{ .Binary }}*"
changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: developerkunal
    name: OpenMorph
